[package]
name = "toy-gdb"
version = "0.1.0"
authors = ["Hagi013 <generativepassion@gmail.com>"]
edition = "2018"

[[bin]]
name = "main"
path = "src/main.rs"

[[bin]]
name = "toy-gdb"
path = "src/toy_gdb.rs"

[dependencies]
anyhow = "1.0.34"
nix = "0.19.0"
rustc-demangle = "0.1.18"
